version: '3'

services:
  app:
    build: . # build from Dockerfile
    container_name: backend
    image: node:18-slim
    ports:
      - 3000:3000
    volumes:
      - .:/home/back-end
    environment:
      DATABASE_URL: ${DATABASE_URL}
    working_dir: /home/back-end
    networks:
      - database
  db:
    container_name: postgresql
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - database

volumes:
  postgres_data:
    driver: local

networks:
  database:
    driver: bridge
